package com.bca.projetoaprendizado.model.vo;
// Generated 24/06/2018 22:58:36 by Hibernate Tools 4.3.1

/**
 * PessoaVO generated by hbm2java
 */
public class PessoaVO implements java.io.Serializable {

    private Integer id;
    private String name;
    private Integer luckynumber;

    public PessoaVO() {
    }

    public PessoaVO(int id, String name, Integer luckynumber) {
        this.id = id;
        this.name = name;

        this.luckynumber = luckynumber;
    }

    public PessoaVO(String name, Integer luckynumber) {
        this.name = name;
        this.luckynumber = luckynumber;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getLuckynumber() {
        return this.luckynumber;
    }

    public void setLuckynumber(Integer luckynumber) {
        this.luckynumber = luckynumber;
    }

}
